# source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LPYCategories_Example'  do
  pod 'LPYCategories', :path => '../'
end

target 'LPYCategories_Tests' do
  pod 'LPYCategories', :path => '../'

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
